// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// These defaults match the unified Thmanyah Supabase project. The
// Overall-Dashboard `build.sh` exports the env vars at build time, so
// these fallbacks only kick in when a developer runs the tool in
// isolation without a .env file.
const FALLBACK_URL = 'https://hbnvbfcwrfanpayxulih.supabase.co';
const FALLBACK_PUBLISHABLE_KEY = 'sb_publishable_P_AoE0x-HsqrJTarwZOT7Q_0UE2trZv';

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = envUrl && envUrl.length > 0 ? envUrl : FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY =
  envKey && envKey.length > 0 ? envKey : FALLBACK_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});