project_id = "jmidpcmotjvyuxsijxsj"

[functions.analyze-commentary]
verify_jwt = true
memory_mb = 1024

[functions.analyze-tweets]
verify_jwt = true

[functions.search-linkedin-candidates]
verify_jwt = true

[functions.analyze-demographics]
verify_jwt = true

[functions.reanalyze-candidate]
verify_jwt = true

[functions.enrich-candidate]
verify_jwt = true
