export interface DummyProfile {
  id: string;
  label: string;
  description: string;
  color: string;
  data: Record<string, string>;
}

export const DUMMY_PROFILES: DummyProfile[] = [
  {
    id: "engineer",
    label: "مهندس برمجيات",
    description: "شاغر مستحدث — دوام كامل — التقنية",
    color: "bg-thmanyah-blue/10 text-thmanyah-blue border-thmanyah-blue/20",
    data: {
      requesterName: "خالد العتيبي",
      requesterEmail: "khaled@thmanyah.com",
      department: "التقنية",
      section: "قسم الهندسة",
      team: "فريق المنصة",
      project: "إعادة بناء المنصة الرقمية",
      budgetOwner: "فهد السبيعي — الرئيس التنفيذي للتقنية",
      vacancyType: "new_position",
      positionsCount: "2",
      isInApprovedStructure: "yes",
      jobTitle: "مهندس برمجيات أول — Full Stack",
      jobTitleEn: "Senior Full Stack Software Engineer",
      jobLevel: "أول (Senior)",
      roleNature: "full_time",
      jobDescription: "تصميم وتطوير الحلول التقنية للمنصة الرقمية باستخدام Next.js و Node.js.\n\nالمهام الرئيسية:\n- قيادة تطوير الميزات الجديدة من التصميم إلى الإطلاق\n- مراجعة الكود وتوجيه المهندسين المبتدئين\n- تحسين أداء وموثوقية المنصة\n- التعاون مع فرق المنتج والتصميم لتحويل المتطلبات إلى حلول تقنية\n- المساهمة في قرارات الهندسة المعمارية",
      country: "السعودية فقط",
      workLocation: "onsite",
      nationality: "saudi",
      triedAlternatives: "yes",
      alternativesDescription: "جربنا توزيع المهام على الفريق الحالي لمدة 3 أشهر لكن الضغط أثر على جودة المخرجات وزاد وقت التسليم بنسبة 40%. كذلك استعنا بمستقل لمدة شهرين لكن طبيعة المشروع تتطلب التزام طويل المدى وفهم عميق للمنظومة.",
      risksIfNotHired: "تأخر إطلاق المنصة الرقمية الجديدة المخطط له في Q3. زيادة الضغط على الفريق الحالي مما قد يؤدي لاستقالات. عدم القدرة على تنفيذ خارطة الطريق التقنية للعام القادم. تراجع تجربة المستخدم بسبب تراكم الديون التقنية.",
      aiRoleIntegration: "يمكن استخدام أدوات AI مثل GitHub Copilot لتسريع كتابة الكود بنسبة 30-40%. كذلك يمكن أتمتة مراجعة الكود الأولية وكتابة الاختبارات باستخدام أدوات AI.",
      aiAutomationPotential: "يمكن أتمتة كتابة الاختبارات الوحدوية، وتوثيق الكود، ومراجعة الأمان الأولية. لكن التصميم المعماري واتخاذ القرارات التقنية الاستراتيجية يتطلب العنصر البشري.",
      aiReplacementAssessment: "الذكاء الاصطناعي يمكنه دعم هذا الدور دعمًا كبيرًا في المهام التشغيلية (كتابة الكود، مراجعته)، لكن لا يمكنه استبداله في فهم سياق الأعمال والتصميم المعماري والتعاون مع الفرق. العنصر البشري أساسي.",
      hiringBarCommitment: "هذه المرة نستهدف مهندس يملك خبرة 5+ سنوات مع سجل واضح في بناء منصات رقمية عالية الأداء. سنضيف تحدي تقني عملي في المقابلة ونتحقق من مهارات التواصل والقيادة التقنية عبر مقابلات مع 3 أعضاء من الفريق.",
      directManagerName: "سعد الحربي",
      directManagerEmail: "saad@thmanyah.com",
      deptCeoName: "فهد السبيعي",
      deptCeoEmail: "fahad@thmanyah.com",
    },
  },
  {
    id: "producer",
    label: "منتج بودكاست",
    description: "شاغر بديل — دوام كامل — الإنتاج",
    color: "bg-thmanyah-green/10 text-emerald-700 border-thmanyah-green/20",
    data: {
      requesterName: "نورة القحطاني",
      requesterEmail: "noura@thmanyah.com",
      department: "الإنتاج",
      section: "قسم البودكاست",
      team: "فريق إنتاج البودكاست",
      project: "برنامج سوالف بزنس",
      budgetOwner: "عمر المالكي — الرئيس التنفيذي للإنتاج",
      vacancyType: "replacement",
      positionsCount: "1",
      previousEmployeeName: "محمد الشهري",
      departureDate: "2026-02-15",
      departureType: "resignation",
      departureReason: "قدم استقالته للانتقال لفرصة خارج المملكة. كان أداؤه ممتازًا وخروجه ترك فجوة واضحة في الفريق خصوصًا في إدارة مرحلة ما بعد الإنتاج والمونتاج الصوتي.",
      jobTitle: "منتج بودكاست أول",
      jobTitleEn: "Senior Podcast Producer",
      jobLevel: "أول (Senior)",
      roleNature: "full_time",
      jobDescription: "إدارة عملية إنتاج البودكاست من الفكرة إلى النشر.\n\nالمهام:\n- التنسيق مع المقدمين والضيوف\n- إدارة جلسات التسجيل\n- الإشراف على المونتاج والماسترنج\n- ضبط الجودة النهائية\n- التنسيق مع فريق التسويق للنشر\n- تطوير أفكار حلقات جديدة",
      country: "السعودية فقط",
      workLocation: "onsite",
      nationality: "saudi",
      triedAlternatives: "no",
      risksIfNotHired: "توقف إنتاج حلقات برنامج سوالف بزنس أو انخفاض ملحوظ في جودتها. الضغط على بقية فريق الإنتاج سيؤثر على جميع البرامج. خطر فقدان الجمهور بسبب عدم الانتظام في النشر.",
      aiRoleIntegration: "يمكن استخدام AI في تفريغ الحلقات تلقائيًا، وتوليد ملخصات للحلقات، وتحسين جودة الصوت باستخدام أدوات مثل Adobe Podcast AI.",
      aiAutomationPotential: "المونتاج الأولي وإزالة الضوضاء وتحسين الصوت يمكن أتمتتها جزئيًا. لكن الحس الإبداعي في اختيار المقاطع وبناء السرد يحتاج العنصر البشري.",
      aiReplacementAssessment: "الذكاء الاصطناعي يمكنه تسريع العمليات التشغيلية بنسبة 25-30% لكنه لا يستطيع استبدال الحس الإبداعي والذوق الصوتي وإدارة العلاقة مع الضيوف. العنصر البشري أساسي وجوهري.",
      hiringBarCommitment: "سنبحث عن منتج لديه محفظة أعمال مميزة في البودكاست العربي وخبرة لا تقل عن 4 سنوات. سنطلب عينة عمل عملية كجزء من المقابلة ونقيّم الذائقة الصوتية والقدرة على السرد.",
      directManagerName: "هند العنزي",
      directManagerEmail: "hind@thmanyah.com",
      deptCeoName: "عمر المالكي",
      deptCeoEmail: "omar@thmanyah.com",
    },
  },
  {
    id: "marketer",
    label: "مسؤول تسويق رقمي",
    description: "شاغر مستحدث خارج الهيكلة — عقد محدد",
    color: "bg-thmanyah-amber/10 text-amber-700 border-thmanyah-amber/20",
    data: {
      requesterName: "ريم الدوسري",
      requesterEmail: "reem@thmanyah.com",
      department: "التسويق",
      section: "قسم التسويق الرقمي",
      team: "فريق النمو",
      project: "حملة إطلاق المنتج الجديد",
      budgetOwner: "سارة العمري — الرئيس التنفيذي للتسويق",
      vacancyType: "new_position",
      positionsCount: "1",
      isInApprovedStructure: "no",
      structureJustification: "نحتاج هذا الدور مؤقتًا (6 أشهر) لدعم حملة إطلاق المنتج الجديد التي تتطلب تكثيف الجهود التسويقية الرقمية. الفريق الحالي لا يستوعب حجم العمل المطلوب في هذه الفترة. بعد انتهاء الحملة، سنقيّم الحاجة لتثبيت الدور ضمن الهيكلة.",
      jobTitle: "مسؤول تسويق رقمي",
      jobTitleEn: "Digital Marketing Specialist",
      jobLevel: "متوسط (Mid-level)",
      roleNature: "contract",
      jobDescription: "إدارة الحملات الإعلانية الرقمية وتحسين معدلات التحويل.\n\nالمهام:\n- إدارة حملات Google Ads و Meta Ads\n- تحليل أداء الحملات وتحسينها\n- إنشاء محتوى إعلاني بالتعاون مع فريق المحتوى\n- إعداد تقارير أسبوعية عن الأداء\n- اختبارات A/B لتحسين معدلات التحويل",
      country: "مرن جغرافيًا",
      workLocation: "remote",
      nationality: "arab",
      triedAlternatives: "yes",
      alternativesDescription: "تعاقدنا مع وكالة تسويق لمدة شهرين لكن النتائج كانت أقل من المتوقع بسبب عدم فهم الوكالة لطبيعة جمهور ثمانية. كذلك حاولنا توزيع المهام على الفريق الحالي لكن التخصص المطلوب غير متوفر.",
      risksIfNotHired: "تأخر حملة الإطلاق مما يؤثر على أهداف النمو للربع القادم. خسارة فرصة تسويقية مهمة في موسم الذروة. عدم تحقيق أهداف الاشتراكات المستهدفة.",
      aiRoleIntegration: "يمكن استخدام AI في كتابة نسخ إعلانية أولية، تحليل بيانات الحملات، وتوليد أفكار للمحتوى. أدوات مثل ChatGPT وMidjourney لإنتاج المحتوى الإبداعي.",
      aiAutomationPotential: "تحليل البيانات وإعداد التقارير يمكن أتمتتها بنسبة كبيرة. كذلك يمكن أتمتة تحسين عروض الأسعار في الحملات الإعلانية.",
      aiReplacementAssessment: "AI يمكنه دعم 40-50% من المهام التشغيلية لكن الاستراتيجية التسويقية وفهم الجمهور والإبداع في الحملات يحتاج العنصر البشري. الدور ممكن يتحول لدور أكثر استراتيجية مع الوقت.",
      hiringBarCommitment: "نبحث عن شخص لديه خبرة مثبتة في حملات رقمية حققت نتائج ملموسة. سنطلب دراسة حالة حقيقية ونقيّم القدرة على التحليل واتخاذ القرارات المبنية على البيانات.",
      directManagerName: "فاطمة الزهراني",
      directManagerEmail: "fatimah@thmanyah.com",
      deptCeoName: "سارة العمري",
      deptCeoEmail: "sarah@thmanyah.com",
    },
  },
  {
    id: "broadcast",
    label: "مهندس بث مباشر",
    description: "5 شواغر — بديل — الإنتاج",
    color: "bg-thmanyah-red/10 text-thmanyah-red border-thmanyah-red/20",
    data: {
      requesterName: "عبدالله القرني",
      requesterEmail: "abdullah@thmanyah.com",
      department: "الإنتاج",
      section: "قسم البث",
      team: "فريق البث المباشر",
      project: "تغطيات الأحداث الحية",
      budgetOwner: "عمر المالكي — الرئيس التنفيذي للإنتاج",
      vacancyType: "replacement",
      positionsCount: "5",
      previousEmployeeName: "فريق البث السابق (5 أشخاص)",
      departureDate: "2026-01-30",
      departureType: "resignation",
      departureReason: "استقال 5 مهندسي بث تباعًا خلال شهرين بسبب عروض منافسة من شركات إعلامية أخرى قدمت رواتب أعلى بنسبة 35-40%. هذا يشير لحاجة مراجعة سلم الرواتب لهذه الوظيفة.",
      jobTitle: "مهندس بث مباشر",
      jobTitleEn: "Live Broadcast Engineer",
      jobLevel: "متوسط (Mid-level)",
      roleNature: "full_time",
      jobDescription: "إدارة وتشغيل البث المباشر للأحداث والبرامج.\n\nالمهام:\n- تجهيز وتشغيل معدات البث المباشر\n- إدارة الصوت والصورة أثناء البث\n- حل المشاكل التقنية الطارئة\n- التنسيق مع فريق الإنتاج\n- صيانة المعدات وتحديثها",
      country: "السعودية فقط",
      workLocation: "onsite",
      nationality: "saudi",
      triedAlternatives: "yes",
      alternativesDescription: "استعنا بشركة إنتاج خارجية لتغطيتين لكن التكلفة كانت 3 أضعاف التكلفة الداخلية والجودة أقل. كذلك حاولنا تدريب موظفين من أقسام أخرى لكن التخصص يحتاج خبرة لا تقل عن سنتين.",
      risksIfNotHired: "عدم القدرة على تنفيذ أي بث مباشر مما يؤثر على 30% من المحتوى المخطط. خسارة عقود رعاية مرتبطة بالبث المباشر. تراجع حضورنا في الأحداث الحية والمناسبات.",
      aiRoleIntegration: "يمكن استخدام AI في التبديل التلقائي بين الكاميرات وتحسين جودة الصورة في الوقت الحقيقي. كذلك أنظمة مراقبة ذكية لاكتشاف المشاكل التقنية مبكرًا.",
      aiAutomationPotential: "بعض المهام التشغيلية مثل ضبط الإضاءة وتوازن الألوان يمكن أتمتتها. لكن إدارة البث الحي وحل المشاكل الطارئة يحتاج تدخل بشري فوري.",
      aiReplacementAssessment: "هذا الدور يتطلب تواجد فيزيائي وتفاعل حي مع المعدات والفريق. الذكاء الاصطناعي يمكنه المساعدة كأداة لكن لا يمكنه استبدال العنصر البشري. أساسي 100%.",
      hiringBarCommitment: "سنركز على استقطاب مهندسين لديهم خبرة في بث الأحداث الكبيرة ونقدم حزمة تنافسية تتناسب مع السوق. سنضيف اختبار عملي في بيئة بث حقيقية.",
      directManagerName: "ماجد الغامدي",
      directManagerEmail: "majed@thmanyah.com",
      deptCeoName: "عمر المالكي",
      deptCeoEmail: "omar@thmanyah.com",
    },
  },
];
